apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-microservice
  template:
    metadata:
      labels:
        app: login-microservice
    spec:
      containers:
        - name: login-microservice
          image: login-microservice:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: login-microservice-service
spec:
  type: NodePort
  selector:
    app: login-microservice
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
